/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Enter;

import static Enter.Register.url;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JButton;
/**
 *
 * @author ThinkPad
 */
public class seat12 extends javax.swing.JFrame {
 private class Seat12ActionListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            JButton btn =(JButton)e.getSource();
            for (int i = 0; i < btns.length; i++){
                if (btn == btns[i]){
                    if (states[i] == 1) {
                        states[i] = 2;
                        btn.setBackground(Color.green);
                       
                    } else if (states[i]==2){
                        states[i] = 1;
                        btn.setBackground(Color.white);
                    } 
                }
            }
        }
        
    }
    
    /**
     * states 0 - 被占用 1 - 可选 2 - 已选
     */
    int[] states = new int[12];
    JButton[] btns = new JButton[12];

    /**
     * Creates new form seat12
     */
    public seat12() {
             this.setUndecorated(true);
        this.setTitle("Choose");
        this.setLocation(400,150);
        initComponents();
        
        // 从数据库拿到信息
        
        Arrays.fill(states, 1);
       
        
        for (int i = 0; i < cp.getComponentCount(); i++) {
            JButton btn = (JButton) cp.getComponent(i);
            btn.addActionListener(new seat12.Seat12ActionListener());
            btns[i] = btn;
        }

        for (int i = 0; i < states.length; i++) {
            int state = states[i];
            
            states[11]=0;
            states[1]=0;
            states[4]=0;
            states[10]=0;
            states[6]=0;
            states[8]=0;
            if (state == 0) {
                btns[i].setBackground(Color.red);
            } else if (state == 1) {
                btns[i].setBackground(Color.white);
            } else {
                btns[i].setBackground(Color.green);
            }
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        cp = new javax.swing.JPanel();
        s1 = new javax.swing.JButton();
        s2 = new javax.swing.JButton();
        s5 = new javax.swing.JButton();
        s6 = new javax.swing.JButton();
        s9 = new javax.swing.JButton();
        s10 = new javax.swing.JButton();
        s3 = new javax.swing.JButton();
        s4 = new javax.swing.JButton();
        s7 = new javax.swing.JButton();
        s8 = new javax.swing.JButton();
        s11 = new javax.swing.JButton();
        s12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        cp.setBackground(new java.awt.Color(204, 204, 204));

        s1.setBorder(null);
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        s2.setBorder(null);
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        s5.setBorder(null);

        s6.setBorder(null);

        s9.setBorder(null);
        s9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s9MouseClicked(evt);
            }
        });
        s9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s9ActionPerformed(evt);
            }
        });

        s10.setBorder(null);
        s10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s10ActionPerformed(evt);
            }
        });

        s3.setBorder(null);
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        s4.setBorder(null);
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });

        s7.setBorder(null);

        s8.setBorder(null);

        s11.setBorder(null);
        s11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s11ActionPerformed(evt);
            }
        });

        s12.setBorder(null);

        javax.swing.GroupLayout cpLayout = new javax.swing.GroupLayout(cp);
        cp.setLayout(cpLayout);
        cpLayout.setHorizontalGroup(
            cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cpLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(135, 135, 135)
                .addGroup(cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        cpLayout.setVerticalGroup(
            cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cpLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(s1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(s2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(s3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(s4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(s5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(s6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(s7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(s8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(s9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(s10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(s11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(s12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        cp.setBounds(40, 130, 691, 294);
        jLayeredPane1.add(cp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Avengers: Endgame");
        jLabel1.setBounds(150, 40, 320, 35);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("11:30  English 3D");
        jLabel2.setBounds(150, 90, 179, 24);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Can not select");
        jLabel3.setBounds(140, 450, 150, 21);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField3.setBackground(new java.awt.Color(255, 0, 0));
        jTextField3.setBounds(110, 450, 24, 24);
        jLayeredPane1.add(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.setBackground(new java.awt.Color(51, 255, 51));
        jTextField1.setBounds(280, 450, 24, 24);
        jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("selected");
        jLabel4.setBounds(310, 450, 110, 21);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.setBounds(410, 450, 24, 24);
        jLayeredPane1.add(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("selectable");
        jLabel5.setBounds(440, 450, 110, 21);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("OK");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(340, 490, 100, 40);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Enter/向左箭头_#ffffff_64_3655826.png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.setBounds(0, 0, 90, 90);
        jLayeredPane1.add(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Enter/c.gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBounds(0, 0, 810, 580);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
      String s11 = "insert into Movie4 values('Avengers','2019.05.20','11:30','Row 1 Column 1','45 ','1','Hall 2','Cinema2')";
       String m11 = "insert into Message (Movie_Name,Movie_Date,Movie_Time,Movie_Seat,Movie_Price,Movie_TF,User_Name,User_Hall,Cinema) values ('Avengers','2019.05.20','11:30','Row 1 Column 1','45 ','1',?,'Hall 2','Cinema2')";
       String ss = "select * from UserMessage";
       PreparedStatement ps = null;ResultSet rs = null;ResultSet rss = null;PreparedStatement pss=null;
        try {
        Class.forName("com.mysql.jdbc.Driver");
        try {
           Connection conn = DriverManager.getConnection(url);
           Statement st=conn.createStatement();
           rs = st.executeQuery(ss);
           Connection con = DriverManager.getConnection(url);
           ps=con.prepareStatement(m11);
           rs.next();
           ps.setString(1, rs.getString("User_Name"));
           ps.executeUpdate();
           
          pss=con.prepareStatement(s11);
          pss.executeUpdate();
           
           
           
           String s = "select * from Movie4 where Movie_Seat='Row 1 Column 1'";
           PreparedStatement pr = con.prepareStatement(s);
           rs =pr.executeQuery();
           
           
           
           int j=0;
           while(rs.next())
           {
               if(rs.getString("Movie_TF").equals("1"))
               {
                   j++;
               }
           }
           if(j%2==0)
           {
               String s2 = "delete  from Movie4 where Movie_Seat='Row 1 Column 1'";
               String m2 = "delete  from Message where Movie_Seat='Row 1 Column 1'";
               ps=con.prepareStatement(s2);
               ps.executeUpdate();
               ps=con.prepareStatement(m2);
               ps.executeUpdate();
           }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_s1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
      String s11 = "insert into Movie4 values('Avengers','2019.05.20','11:30','Row 1 Column 2','45 ','1','Hall 2','Cinema2')";
       String m11 = "insert into Message (Movie_Name,Movie_Date,Movie_Time,Movie_Seat,Movie_Price,Movie_TF,User_Name,User_Hall,Cinema) values ('Avengers','2019.05.20','11:30','Row 1 Column 2','45 ','1',?,'Hall 2','Cinema2')";
       String ss = "select * from UserMessage";
       PreparedStatement ps = null;ResultSet rs = null;ResultSet rss = null;PreparedStatement pss=null;
        try {
        Class.forName("com.mysql.jdbc.Driver");
        try {
           Connection conn = DriverManager.getConnection(url);
           Statement st=conn.createStatement();
           rs = st.executeQuery(ss);
           Connection con = DriverManager.getConnection(url);
           ps=con.prepareStatement(m11);
           rs.next();
           ps.setString(1, rs.getString("User_Name"));
           ps.executeUpdate();
           
          pss=con.prepareStatement(s11);
          pss.executeUpdate();
           
           
           
           String s = "select * from Movie4 where Movie_Seat='Row 1 Column 2'";
           PreparedStatement pr = con.prepareStatement(s);
           rs =pr.executeQuery();
           
           
           
           int j=0;
           while(rs.next())
           {
               if(rs.getString("Movie_TF").equals("1"))
               {
                   j++;
               }
           }
           if(j%2==0)
           {
               String s2 = "delete  from Movie4 where Movie_Seat='Row 1 Column 2'";
               String m2 = "delete  from Message where Movie_Seat='Row 1 Column 2'";
               ps=con.prepareStatement(s2);
               ps.executeUpdate();
               ps=con.prepareStatement(m2);
               ps.executeUpdate();
           }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_s2ActionPerformed

    private void s9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s9MouseClicked

   }//GEN-LAST:event_s9MouseClicked

    private void s9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s9ActionPerformed
       String s11 = "insert into Movie4 values('Avengers','2019.05.20','11:30','Row 3 Column 1','45 ','1','Hall 2','Cinema2')";
       String m11 = "insert into Message (Movie_Name,Movie_Date,Movie_Time,Movie_Seat,Movie_Price,Movie_TF,User_Name,User_Hall,Cinema) values ('Avengers','2019.05.20','11:30','Row 3 Column 1','45 ','1',?,'Hall 2','Cinema2')";
       String ss = "select * from UserMessage";
       PreparedStatement ps = null;ResultSet rs = null;ResultSet rss = null;PreparedStatement pss=null;
        try {
        Class.forName("com.mysql.jdbc.Driver");
        try {
           Connection conn = DriverManager.getConnection(url);
           Statement st=conn.createStatement();
           rs = st.executeQuery(ss);
           Connection con = DriverManager.getConnection(url);
           ps=con.prepareStatement(m11);
           rs.next();
           ps.setString(1, rs.getString("User_Name"));
           ps.executeUpdate();
           
          pss=con.prepareStatement(s11);
          pss.executeUpdate();
           
           
           
           String s = "select * from Movie4 where Movie_Seat='Row 3 Column 1'";
           PreparedStatement pr = con.prepareStatement(s);
           rs =pr.executeQuery();
           
           
           
           int j=0;
           while(rs.next())
           {
               if(rs.getString("Movie_TF").equals("1"))
               {
                   j++;
               }
           }
           if(j%2==0)
           {
               String s2 = "delete  from Movie4 where Movie_Seat='Row 3 Column 1'";
               String m2 = "delete  from Message where Movie_Seat='Row 3 Column 1'";
               ps=con.prepareStatement(s2);
               ps.executeUpdate();
               ps=con.prepareStatement(m2);
               ps.executeUpdate();
           }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_s9ActionPerformed

    private void s10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s10ActionPerformed
        String s11 = "insert into Movie4 values('Avengers','2019.05.20','11:30','Row 3 Column 2','45 ','1','Hall 2','Cinema2')";
       String m11 = "insert into Message (Movie_Name,Movie_Date,Movie_Time,Movie_Seat,Movie_Price,Movie_TF,User_Name,User_Hall,Cinema) values ('Avengers','2019.05.20','11:30','Row 3 Column 2','45 ','1',?,'Hall 2','Cinema2')";
       String ss = "select * from UserMessage";
       PreparedStatement ps = null;ResultSet rs = null;ResultSet rss = null;PreparedStatement pss=null;
        try {
        Class.forName("com.mysql.jdbc.Driver");
        try {
           Connection conn = DriverManager.getConnection(url);
           Statement st=conn.createStatement();
           rs = st.executeQuery(ss);
           Connection con = DriverManager.getConnection(url);
           ps=con.prepareStatement(m11);
           rs.next();
           ps.setString(1, rs.getString("User_Name"));
           ps.executeUpdate();
           
          pss=con.prepareStatement(s11);
          pss.executeUpdate();
           
           
           
           String s = "select * from Movie4 where Movie_Seat='Row 3 Column 2'";
           PreparedStatement pr = con.prepareStatement(s);
           rs =pr.executeQuery();
           
           
           
           int j=0;
           while(rs.next())
           {
               if(rs.getString("Movie_TF").equals("1"))
               {
                   j++;
               }
           }
           if(j%2==0)
           {
               String s2 = "delete  from Movie4 where Movie_Seat='Row 3 Column 2'";
               String m2 = "delete  from Message where Movie_Seat='Row 3 Column 2'";
               ps=con.prepareStatement(s2);
               ps.executeUpdate();
               ps=con.prepareStatement(m2);
               ps.executeUpdate();
           }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_s10ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
       String s11 = "insert into Movie4 values('Avengers','2019.05.20','11:30','Row 1 Column 3','45 ','1','Hall 2','Cinema2')";
       String m11 = "insert into Message (Movie_Name,Movie_Date,Movie_Time,Movie_Seat,Movie_Price,Movie_TF,User_Name,User_Hall,Cinema) values ('Avengers','2019.05.20','11:30','Row 1 Column 3','45 ','1',?,'Hall 2','Cinema2')";
       String ss = "select * from UserMessage";
       PreparedStatement ps = null;ResultSet rs = null;ResultSet rss = null;PreparedStatement pss=null;
        try {
        Class.forName("com.mysql.jdbc.Driver");
        try {
           Connection conn = DriverManager.getConnection(url);
           Statement st=conn.createStatement();
           rs = st.executeQuery(ss);
           Connection con = DriverManager.getConnection(url);
           ps=con.prepareStatement(m11);
           rs.next();
           ps.setString(1, rs.getString("User_Name"));
           ps.executeUpdate();
           
          pss=con.prepareStatement(s11);
          pss.executeUpdate();
           
           
           
           String s = "select * from Movie4 where Movie_Seat='Row 1 Column 3'";
           PreparedStatement pr = con.prepareStatement(s);
           rs =pr.executeQuery();
           
           
           
           int j=0;
           while(rs.next())
           {
               if(rs.getString("Movie_TF").equals("1"))
               {
                   j++;
               }
           }
           if(j%2==0)
           {
               String s2 = "delete  from Movie4 where Movie_Seat='Row 1 Column 3'";
               String m2 = "delete  from Message where Movie_Seat='Row 1 Column 3'";
               ps=con.prepareStatement(s2);
               ps.executeUpdate();
               ps=con.prepareStatement(m2);
               ps.executeUpdate();
           }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed

String s11 = "insert into Movie4 values('Avengers','2019.05.20','11:30','Row 1 Column 4','45 ','1','Hall 2','Cinema2')";
       String m11 = "insert into Message (Movie_Name,Movie_Date,Movie_Time,Movie_Seat,Movie_Price,Movie_TF,User_Name,User_Hall,Cinema) values ('Avengers','2019.05.20','11:30','Row 1 Column 4','45 ','1',?,'Hall 2','Cinema2')";
       String ss = "select * from UserMessage";
       PreparedStatement ps = null;ResultSet rs = null;ResultSet rss = null;PreparedStatement pss=null;
        try {
        Class.forName("com.mysql.jdbc.Driver");
        try {
           Connection conn = DriverManager.getConnection(url);
           Statement st=conn.createStatement();
           rs = st.executeQuery(ss);
           Connection con = DriverManager.getConnection(url);
           ps=con.prepareStatement(m11);
           rs.next();
           ps.setString(1, rs.getString("User_Name"));
           ps.executeUpdate();
           
          pss=con.prepareStatement(s11);
          pss.executeUpdate();
           
           
           
           String s = "select * from Movie4 where Movie_Seat='Row 1 Column 4'";
           PreparedStatement pr = con.prepareStatement(s);
           rs =pr.executeQuery();
           
           
           
           int j=0;
           while(rs.next())
           {
               if(rs.getString("Movie_TF").equals("1"))
               {
                   j++;
               }
           }
           if(j%2==0)
           {
               String s2 = "delete  from Movie4 where Movie_Seat='Row 1 Column 4'";
               String m2 = "delete  from Message where Movie_Seat='Row 1 Column 4'";
               ps=con.prepareStatement(s2);
               ps.executeUpdate();
               ps=con.prepareStatement(m2);
               ps.executeUpdate();
           }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_s4ActionPerformed

    private void s11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s11ActionPerformed
        String s111 = "insert into Movie4 values('Advengers','','11:30','Row 3 Column 3','68','1')";

        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {

                Connection con = DriverManager.getConnection(url);
                ps = con.prepareStatement(s111);
                ps.executeUpdate();

                String s = "select * from Movie4 where Movie_Seat='Row 3 Column 3'";
                PreparedStatement pr = con.prepareStatement(s);
                rs = pr.executeQuery();
                int j = 0;
                while (rs.next()) {
                    if (rs.getString("Movie_TF").equals("1")) {
                        j++;
                    }
                }
                if (j % 2 == 0) {
                    String s2 = "delete  from Movie4 where Movie_Seat='Row 3 Column 3'";
                    ps = con.prepareStatement(s2);
                    ps.executeUpdate();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_s11ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                Connection conn = DriverManager.getConnection(url);

                String s = "select * from Movie4";
                PreparedStatement pr = conn.prepareStatement(s);
                ResultSet rs = pr.executeQuery();

                int i = 0;
                while (rs.next()) {
                    if (rs.getString("Movie_TF").equals("1")) {
                        i++;
                    }
                }
                if (i == 0) {
                    new SeatZero().setVisible(true);
                    this.dispose();
                } else {
                    new Pay2().setVisible(true);
                    this.dispose();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new Ac1().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seat12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seat12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seat12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seat12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new seat12().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cp;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton s1;
    private javax.swing.JButton s10;
    private javax.swing.JButton s11;
    private javax.swing.JButton s12;
    private javax.swing.JButton s2;
    private javax.swing.JButton s3;
    private javax.swing.JButton s4;
    private javax.swing.JButton s5;
    private javax.swing.JButton s6;
    private javax.swing.JButton s7;
    private javax.swing.JButton s8;
    private javax.swing.JButton s9;
    // End of variables declaration//GEN-END:variables
}
